/**
 * Employment Verification helper — server-only.
 * Creates a DB row and sends the employer form link via email.
 *
 * Call this from two places:
 *  1. After addTenant() — when employer info is captured (see actions.ts TODO).
 *  2. After a re-rent / new lease is created on a property.
 */

import { createSupabaseAdminClient } from '@/lib/supabase';
import { sendEmployerVerificationRequestEmail } from '@/lib/email';

export interface SendEmploymentVerificationParams {
  tenantId: string;
  landlordId: string;
  propertyId: string;
  employerEmail: string;
  employerName: string | null;
  employerContactName: string | null;
}

const BASE_URL =
  process.env.NEXT_PUBLIC_SITE_URL?.startsWith('http://localhost')
    ? 'https://portal.rental911.net'
    : (process.env.NEXT_PUBLIC_SITE_URL ?? 'https://portal.rental911.net');

/**
 * Creates an employment_verifications row and emails the employer.
 * Non-throwing — returns { ok: false, error } on failure so callers can log and continue.
 */
export async function sendEmploymentVerification(
  params: SendEmploymentVerificationParams
): Promise<{ ok: boolean; error?: string; verificationId?: string }> {
  const admin = createSupabaseAdminClient();

  // Look up tenant name for the email subject
  const { data: tenant } = await admin
    .from('users')
    .select('full_name, email')
    .eq('id', params.tenantId)
    .maybeSingle();

  const tenantName = tenant?.full_name ?? tenant?.email ?? 'your applicant';

  // Create the employment_verifications row (token auto-generated by DB default)
  const { data: record, error: insertError } = await admin
    .from('employment_verifications')
    .insert({
      tenant_id: params.tenantId,
      landlord_id: params.landlordId,
      property_id: params.propertyId,
      employer_name: params.employerName,
      employer_email: params.employerEmail,
      employer_contact_name: params.employerContactName,
    })
    .select('id, token')
    .single();

  if (insertError || !record) {
    console.error('[employment-verification] DB insert failed:', insertError);
    return { ok: false, error: insertError?.message ?? 'DB insert failed' };
  }

  const formUrl = `${BASE_URL}/verify-employment/${record.token}`;

  const sent = await sendEmployerVerificationRequestEmail({
    to: [params.employerEmail],
    tenantName,
    employerContactName: params.employerContactName ?? undefined,
    formUrl,
  });

  if (!sent) {
    console.warn(
      '[employment-verification] Email failed to send; record still created.',
      { verificationId: record.id }
    );
  }

  return { ok: true, verificationId: record.id };
}
